[package]
name = "kba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
num-traits = "0.2.16"
proc-bitfield = "0.3.0"
sdl2 = "0.35.2"
